export const BLOCK_SIZE = 65
export const BLOCKS_IN_ROW = 8
export const BLOCKS_IN_COLUMN = BLOCKS_IN_ROW

export const FIELD_PADDING = 15
export const FIELD_SIZE = BLOCK_SIZE * BLOCKS_IN_ROW + FIELD_PADDING * 2

export const BLOCKS_QUANTITY = BLOCKS_IN_ROW * BLOCKS_IN_COLUMN

